networks:
  app-network:
    driver: bridge

# Persistent Volumes
volumes:
  postgres_data: # Persistent storage for PostgreSQL
    name: joo-joo-postgres-data

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:17-bookworm # Stable PostgreSQL image (Debian-based)
    container_name: joo-joo-postgres-dev

    restart: unless-stopped # Restart unless manually stopped
  
    environment:
      - POSTGRES_DB=joojoo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

    networks:
      - app-network # Internal app network

    logging:
      driver: json-file # Default Docker logging driver
      options:
        max-size: "10m" # Rotate logs after 10MB
        max-file: "5" # Keep max 5 log files

  api:
    build:
      context: .
      dockerfile: infra/docker/api.dockerfile
    container_name: joo-joo-api

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped # Restart unless manually stopped

    environment:
      - PORT=4000
      - NODE_ENV=development
      - ORIGIN=http://localhost:3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/joojoo
      - ACCESS_JWT_SECRET=YOUR_ACCESS_JWT_SECRET_KEY
      - REFRESH_JWT_SECRET=YOUR_REFRESH_JWT_SECRET_KEY

    ports:
      - "${PORT:-4000}:4000"

    networks:
      - app-network # Internal app network

    logging:
      driver: json-file # Default Docker logging driver
      options:
        max-size: "10m" # Rotate logs after 10MB
        max-file: "5" # Keep max 5 log files

  web:
    build:
      context: .
      dockerfile: infra/docker/web.dockerfile
    container_name: joo-joo-web

    depends_on:
      api:
        condition: service_started

    restart: unless-stopped # Restart unless manually stopped

    ports:
      - "3000:3000"

    networks:
      - app-network # Internal app network

    logging:
      driver: json-file # Default Docker logging driver
      options:
        max-size: "10m" # Rotate logs after 10MB
        max-file: "5" # Keep max 5 log files
    